version: '3.7'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_ARBITRARY: '1'
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_HOSTS: 'mysql_55,mysql_57,mysql_8'
    links:
      - mysql_55
      - mysql_57
      - mysql_8
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - './var/pgadmin:/var/lib/pgadmin'
    ports:
      - '8082:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: info@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    links:
      - pgsql_96
      - pgsql_10
  mysql_55:
    build:
      context: docker/mysql
      args: { VERSION: 5.5 }
    volumes:
      - './var/mysql/5.5:/var/lib/mysql'
    ports:
      - '33060:3306'
  mysql_57:
    build:
      context: docker/mysql
      args: { VERSION: 5.7 }
    volumes:
      - './var/mysql/5.7:/var/lib/mysql'
    ports:
      - '33061:3306'
  mysql_8:
    build:
      context: docker/mysql
      args: { VERSION: !!float 8 }
    volumes:
      - './var/mysql/8:/var/lib/mysql'
    ports:
      - '33062:3306'
  pgsql_96:
    build:
      context: docker/postgres
      args: { VERSION: 9.6 }
    volumes:
      - './var/pgsql/9.6:/var/lib/postgresql/data'
    ports:
      - '54320:5432'
  pgsql_10:
    build:
      context: docker/postgres
      args: { VERSION: !!float 10 }
    volumes:
      - './var/pgsql/10:/var/lib/postgresql/data'
    ports:
      - '54321:5432'
